<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LPCAIQ1132" failures="0" tests="5" name="Cucumber_TestRunner.testRunner3" time="30.076" errors="0" timestamp="2023-01-01T11:59:47 EET" skipped="0">
  <testcase classname="Cucumber_TestRunner.testRunner3" name="runScenario" time="6.000"/>
  <system-out>
    <![CDATA[The ‘Username’ used for this test run is:>> [Admin]
The ‘Password’ used for this test run is:>> [admin123]]]>
  </system-out>
  <testcase classname="Cucumber_TestRunner.testRunner3" name="runScenario" time="5.324"/>
  <system-out>
    <![CDATA[The ‘Username’ used for this test run is:>> [admin123]
The ‘Password’ used for this test run is:>> [Admin]
The invalid credentials error message was displayed and has been asserted || Test case passed]]>
  </system-out>
  <testcase classname="Cucumber_TestRunner.testRunner3" name="runScenario" time="8.387"/>
  <system-out>
    <![CDATA[The ‘Username’ used for this test run is:>> [Admin]
The ‘Password’ used for this test run is:>> [admin123]]]>
  </system-out>
  <testcase classname="Cucumber_TestRunner.testRunner3" name="runScenario" time="5.900"/>
  <system-out>
    <![CDATA[The ‘Username’ used for this test run is:>> []
The ‘Password’ used for this test run is:>> []
All fields error message were displayed and has been asserted || Test case passed]]>
  </system-out>
  <testcase classname="Cucumber_TestRunner.testRunner3" name="runScenario" time="4.465"/>
  <system-out/>
</testsuite> <!-- Cucumber_TestRunner.testRunner3 -->
